// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RevisionAI.Infrastructure.Data;

#nullable disable

namespace RevisionAI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603205756_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RevisionAI.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AchievementKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AchievementKey")
                        .IsUnique();

                    b.ToTable("Achievements", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.BookmarkCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BookmarkCollections", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.BookmarkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("CollectionId", "QuestionId")
                        .IsUnique();

                    b.ToTable("BookmarkItems", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer");

                    b.Property<int>("EndPage")
                        .HasColumnType("integer");

                    b.Property<int>("StartPage")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique();

                    b.ToTable("Friendships", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.MockSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MockConfig")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MockSessions", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.MockSessionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MockSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<char?>("SelectedOption")
                        .HasColumnType("char(1)");

                    b.Property<int?>("TimeTakenMs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MockSessionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("MockSessionId", "QuestionId")
                        .IsUnique();

                    b.ToTable("MockSessionAnswers", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.PendingQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAnswered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsAnswered", "ExpiresAt");

                    b.ToTable("PendingQuestions", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<char>("CorrectOption")
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("ExamName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPYQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourcePage")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("IsPYQ");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TopicId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.QuestionMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionMedia", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.QuestionSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("EaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(2.5);

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Repetitions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NextReviewDate");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "QuestionId")
                        .IsUnique();

                    b.ToTable("QuestionSchedules", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IconName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Subjects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01000000-2423-2625-2728-292a2b2c2d2e"),
                            Name = "Anaesthesia",
                            Slug = "anaesthesia"
                        },
                        new
                        {
                            Id = new Guid("02000000-4342-4544-4647-48494a4b4c4d"),
                            Name = "Anatomy",
                            Slug = "anatomy"
                        },
                        new
                        {
                            Id = new Guid("03000000-6261-6463-6566-6768696a6b6c"),
                            Name = "Biochemistry",
                            Slug = "biochemistry"
                        },
                        new
                        {
                            Id = new Guid("04000000-8180-8382-8485-868788898a8b"),
                            Name = "Community Medicine",
                            Slug = "community-medicine"
                        },
                        new
                        {
                            Id = new Guid("05000000-a09f-a2a1-a3a4-a5a6a7a8a9aa"),
                            Name = "Dermatology",
                            Slug = "dermatology"
                        },
                        new
                        {
                            Id = new Guid("06000000-bfbe-c1c0-c2c3-c4c5c6c7c8c9"),
                            Name = "ENT",
                            Slug = "ent"
                        },
                        new
                        {
                            Id = new Guid("07000000-dedd-e0df-e1e2-e3e4e5e6e7e8"),
                            Name = "Forensic Medicine",
                            Slug = "forensic-medicine"
                        },
                        new
                        {
                            Id = new Guid("08000000-fdfc-fffe-0001-020304050607"),
                            Name = "Medicine",
                            Slug = "medicine"
                        },
                        new
                        {
                            Id = new Guid("09000000-1c1b-1e1d-1f20-212223242526"),
                            Name = "Microbiology",
                            Slug = "microbiology"
                        },
                        new
                        {
                            Id = new Guid("0a000000-3b3a-3d3c-3e3f-404142434445"),
                            Name = "OB GYN",
                            Slug = "ob-gyn"
                        },
                        new
                        {
                            Id = new Guid("0b000000-5a59-5c5b-5d5e-5f6061626364"),
                            Name = "Ophthalmology",
                            Slug = "ophthalmology"
                        },
                        new
                        {
                            Id = new Guid("0c000000-7978-7b7a-7c7d-7e7f80818283"),
                            Name = "Orthopedics",
                            Slug = "orthopedics"
                        },
                        new
                        {
                            Id = new Guid("0d000000-9897-9a99-9b9c-9d9e9fa0a1a2"),
                            Name = "Pathology",
                            Slug = "pathology"
                        },
                        new
                        {
                            Id = new Guid("0e000000-b7b6-b9b8-babb-bcbdbebfc0c1"),
                            Name = "Pediatrics",
                            Slug = "pediatrics"
                        },
                        new
                        {
                            Id = new Guid("0f000000-d6d5-d8d7-d9da-dbdcdddedfe0"),
                            Name = "Pharmacology",
                            Slug = "pharmacology"
                        },
                        new
                        {
                            Id = new Guid("10000000-f5f4-f7f6-f8f9-fafbfcfdfeff"),
                            Name = "Physiology",
                            Slug = "physiology"
                        },
                        new
                        {
                            Id = new Guid("11000000-1413-1615-1718-191a1b1c1d1e"),
                            Name = "Psychiatry",
                            Slug = "psychiatry"
                        },
                        new
                        {
                            Id = new Guid("12000000-3332-3534-3637-38393a3b3c3d"),
                            Name = "Radiology",
                            Slug = "radiology"
                        },
                        new
                        {
                            Id = new Guid("13000000-5251-5453-5556-5758595a5b5c"),
                            Name = "Surgery",
                            Slug = "surgery"
                        });
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<int?>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("\"GoogleId\" IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.UserAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Confidence")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<char>("SelectedOption")
                        .HasColumnType("char(1)");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TimeTakenMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "QuestionId");

                    b.ToTable("UserAttempts", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.UserNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotes", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.UserStreak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateOnly?>("LastActiveDate")
                        .HasColumnType("date");

                    b.Property<int>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStreaks", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.UserXp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("TotalXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserXp", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.XpTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("XpTransactions", (string)null);
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Achievement", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.BookmarkCollection", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.User", "User")
                        .WithMany("BookmarkCollections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.BookmarkItem", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.BookmarkCollection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RevisionAI.Domain.Entities.Question", "Question")
                        .WithMany("BookmarkItems")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Chapter", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.User", "Addressee")
                        .WithMany("ReceivedFriendships")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RevisionAI.Domain.Entities.User", "Requester")
                        .WithMany("RequestedFriendships")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.MockSession", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.User", "User")
                        .WithMany("MockSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.MockSessionAnswer", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.MockSession", "MockSession")
                        .WithMany("Answers")
                        .HasForeignKey("MockSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RevisionAI.Domain.Entities.Question", "Question")
                        .WithMany("MockSessionAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MockSession");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.PendingQuestion", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.Question", "Question")
                        .WithMany("PendingQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RevisionAI.Domain.Entities.User", "User")
                        .WithMany("PendingQuestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Question", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Questions")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RevisionAI.Domain.Entities.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RevisionAI.Domain.Entities.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("Subject");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.QuestionMedia", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.Question", "Question")
                        .WithMany("Media")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.QuestionSchedule", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.Question", "Question")
                        .WithMany("Schedules")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RevisionAI.Domain.Entities.User", "User")
                        .WithMany("QuestionSchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Topic", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Topics")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.UserAttempt", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.Question", "Question")
                        .WithMany("UserAttempts")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RevisionAI.Domain.Entities.User", "User")
                        .WithMany("UserAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.UserNote", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.Question", "Question")
                        .WithMany("UserNotes")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RevisionAI.Domain.Entities.Topic", "Topic")
                        .WithMany("UserNotes")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RevisionAI.Domain.Entities.User", "User")
                        .WithMany("UserNotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.UserStreak", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.User", "User")
                        .WithOne("Streak")
                        .HasForeignKey("RevisionAI.Domain.Entities.UserStreak", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.UserXp", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.User", "User")
                        .WithOne("Xp")
                        .HasForeignKey("RevisionAI.Domain.Entities.UserXp", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.XpTransaction", b =>
                {
                    b.HasOne("RevisionAI.Domain.Entities.Question", "Question")
                        .WithMany("XpTransactions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RevisionAI.Domain.Entities.User", "User")
                        .WithMany("XpTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.BookmarkCollection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Chapter", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.MockSession", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Question", b =>
                {
                    b.Navigation("BookmarkItems");

                    b.Navigation("Media");

                    b.Navigation("MockSessionAnswers");

                    b.Navigation("PendingQuestions");

                    b.Navigation("Schedules");

                    b.Navigation("UserAttempts");

                    b.Navigation("UserNotes");

                    b.Navigation("XpTransactions");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.Topic", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("UserNotes");
                });

            modelBuilder.Entity("RevisionAI.Domain.Entities.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("BookmarkCollections");

                    b.Navigation("MockSessions");

                    b.Navigation("PendingQuestions");

                    b.Navigation("QuestionSchedules");

                    b.Navigation("ReceivedFriendships");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RequestedFriendships");

                    b.Navigation("Streak");

                    b.Navigation("UserAttempts");

                    b.Navigation("UserNotes");

                    b.Navigation("Xp");

                    b.Navigation("XpTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
